[phases.setup]
nixPkgs = ['nodejs-18_x', 'nodePackages.npm']
aptPkgs = ['build-essential']

[environment]
NIXPACKS_NODE_VERSION = "18"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
run = "npm run start"